#!/bin/sh
# set -e

IPTABLES_EXEC="/sbin/ip6tables"
IPTABLES_ERR_LOG="/tmp/ip6tables.err"
LOG_ERROR='shell_log ip6tables error '

$IPTABLES_EXEC -w $* 2> $IPTABLES_ERR_LOG
ret=$?
if [ $ret -ne 0 ]; then
    $LOG_ERROR "[$ret]: $(cat $IPTABLES_ERR_LOG) :: $IPTABLES_EXEC $*"
fi
